use mysql;
CREATE DATABASE IF NOT EXISTS mc_iam CHARSET=UTF8MB4;
CREATE DATABASE IF NOT EXISTS mc_itsm CHARSET=UTF8MB4;
CREATE DATABASE IF NOT EXISTS mc_mns CHARSET=UTF8MB4;
CREATE DATABASE IF NOT EXISTS mc_ucenter CHARSET=UTF8MB4;
CREATE DATABASE IF NOT EXISTS mc_schedule CHARSET=UTF8MB4;
